manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mun5424
      url-base: https://github.com/mun5424
  projects:
    - name: zmk
      remote: mun5424
      revision: sofle
      import: app/west.yml
  self:
    path: config
